const faker = require('faker')

const helpers = require('../helpers/helpers')

const jobStatuses = [
    'quoted',
    'quote accepted',
    'in-progress',
    'complete'
]

// CREATE JOB RECORD FUNCTION
function createJob(db, customerId, job) {

    // Paramaterise the values we want to put in the database
    const parameters = {
        $customer_id: customerId,
        $quote: job.quote,
        $job_description: job.jobDescription,
        $job_status: job.status
    }

    // Create a SQL statement with the placeholders
    const sql = `
    INSERT INTO jobs(customer_id, quote, job_description, job_status) 
    VALUES ($customer_id, $quote, $job_description, $job_status);
    `

    // Create a promise to we can resolve the id for the record generated by the statement or return an error
    return new Promise((resolve, reject) => {
        db.run(
            sql,
            parameters,
            function (error, result) {
                if (error) {
                    reject(error)
                }
                console.log('JOB THIS:', this.lastID)
                resolve(this.lastID)
            })
    })
}

function createMockJob(customerId) {
    return {
        customerId: `${helpers.randomNumberInRange(0, 1000000) || customerId}`,
        quote: `${faker.commerce.price(1000, 10000)}`,
        jobDescription: `${faker.lorem.paragraphs(5)}`,
        status: `${jobStatuses[helpers.randomNumberInRange(0, 3)]}`
    }
}

module.exports = {
    createJob,
    createMockJob,
    jobStatuses
}